//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lepasi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class marka
    {
        public marka()
        {
            this.samochods = new HashSet<samochod>();
        }

        [Display(Name = "ID Marki")]
        public int MA_id { get; set; }
        [Display(Name = "Marka")]
        public string MA_nazwa { get; set; }
    
        public virtual ICollection<samochod> samochods { get; set; }
    }
}
