//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lepasi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class samochod
    {
        public static object samochody { get; internal set; }
        [Required]
        public int Id { get; set; }
        [Display(Name = "ID Samochodu")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        public int SA_id { get; set; }
        [Display(Name = "Typ")]
        public int TY_id { get; set; }
        [Display(Name = "ID Marki")]
        public int MA_id { get; set; }
        [Display(Name = "ID Stanu")]
        public int ST_id { get; set; }
        [Display(Name = "Model")]
        public string SA_model { get; set; }
        [Display(Name = "Stan")]
        public string SA_stan { get; set; }
        [Display(Name = "Cena")]
        public Nullable<decimal> SA_cena { get; set; }
        [Display(Name = "Kolor")]
        public string SA_kolor { get; set; }
        [Display(Name = "Rok produkcji")]
        public Nullable<int> SA_rok_produkcji { get; set; }
        [Display(Name = "Kraj pochodzenia")]
        public string SA_kraj_pochodzenia { get; set; }
        [Display(Name = "Liczba miejsc")]
        public Nullable<int> SA_liczba_miejsc { get; set; }

        [Display(Name = "Marka")]
        public virtual marka marka { get; set; }
        [Display(Name = "Status")]
        public virtual status status { get; set; }
        [Display(Name = "Typ")]
        public virtual typ typ { get; set; }
    }
}
