//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lepasi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class typ
    {
        public typ()
        {
            this.samochods = new HashSet<samochod>();
        }

        [Display(Name = "ID Typu")]
        public int TY_id { get; set; }
        [Display(Name = "Typ")]
        public string TY_nazwa { get; set; }
    
        public virtual ICollection<samochod> samochods { get; set; }
    }
}
